# Generated by Django 4.1.7 on 2023-04-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_code', models.CharField(max_length=200)),
                ('a_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(max_length=200)),
                ('c_category', models.CharField(max_length=200)),
                ('c_size', models.CharField(max_length=200)),
                ('c_color', models.CharField(max_length=200)),
                ('c_price', models.CharField(max_length=200)),
                ('c_count', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=200)),
                ('u_pw', models.CharField(max_length=200)),
                ('a_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.address')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_code', models.CharField(max_length=200)),
                ('r_title', models.CharField(max_length=200)),
                ('r_content', models.CharField(max_length=200)),
                ('r_star', models.CharField(max_length=200)),
                ('r_size', models.CharField(max_length=200)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(max_length=200)),
                ('c_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cloth')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_code', models.CharField(max_length=200)),
                ('c_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cloth')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
